version: '3'
services:
  mapserver:
    build: .
    ports:
      - "80:80"
    environment:
      # Variabili per abilitare e configurare il caching di GDAL per VSICURL
      - CPL_VSIL_CURL_CACHE=/tmp/vsicurl_cache
      - CPL_VSIL_CURL_CACHE_SIZE=1000000000  # 1GB di cache (modifica se necessario)
